spring:
  application:
    name: spring-ai-functions
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4
api-ninjas:
  api-key: ${API_NINJAS_KEY}
  api-url:
    stock-price: https://api.api-ninjas.com/v1/stockprice